module.exports = {
  free: {
    id: "free",
    name: "Starter",
    price: 0,
    currency: "USD",
    interval: "month",
    features: {
      maxProducts: 10,
      maxCustomers: 20,
      maxInvoices: 5,
      maxUsers: 1,
      reports: false,
      apiAccess: false,
    },
    limits: {
      products: 10,
      customers: 20,
      invoices: 5,
      users: 1,
      sales: 10,
    },
  },
  pro: {
    id: "pro",
    name: "Professional",
    price: 29,
    currency: "USD",
    interval: "month",
    features: {
      maxProducts: 100,
      maxCustomers: 500,
      maxInvoices: 100,
      maxUsers: 5,
      reports: true,
      apiAccess: true,
    },
    limits: {
      products: 100,
      customers: 500,
      invoices: 100,
      users: 5,
      sales: 500,
    },
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    price: 99,
    currency: "USD",
    interval: "month",
    features: {
      maxProducts: Infinity,
      maxCustomers: Infinity,
      maxInvoices: Infinity,
      maxUsers: 20,
      reports: true,
      apiAccess: true,
    },
    limits: {
      products: Infinity,
      customers: Infinity,
      invoices: Infinity,
      users: 20,
      sales: Infinity,
    },
  },
};
